backend:
  name: github
  repo: razytech/Razy-Tech
  branch: master
  # name: git-gateway
  # repo: osamajandali/Razy-Tech
  # branch: master

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
display_url: razy-tech.netlify.com

collections:
  - name: "pages"
    label: "Pages"
    delete: false
    editor:
      preview: false
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Short Description, name: short_desc, widget: object, fields:[{label: Title, name: title, widget: string }, {label: Description, name: description, widget: text }, {label: paragraph1, name: paragraph1, widget: text }, {label: paragraph2, name: paragraph2, widget: text }, {label: paragraph3, name: paragraph3, widget: text }]}
          - {label: Solutions, name: solutions, widget: object, fields:[{label: Title, name: title, widget: string }, {label: Description, name: description, widget: text }, {label: Solution 1, name: sol1, widget: string }, {label: Solution 2, name: sol2, widget: string }, {label: Solution 3, name: sol3, widget: string }, {label: Solution 4, name: sol4, widget: string }]}
          - {label: Clients, name: clients, widget: list, fields: [{label: Logo, name: logo, widget: image}]}
          - {label: "Meta Title", name: "meta_title", widget: "string"}
          - {label: "Meta Description", name: "meta_description", widget: "text"}
      - file: "src/pages/about/index.md"
        label: "About"  
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Image", name: hero_image, widget: image}
          - {label: "Page Description", name: "page_description", widget: "object", fields:[{label: "Title", name: "title", widget: "string"}, {label: "Text", name: "text", widget: "text"}] }
          - {label: "Bussiness Structure", name: "bussiness_structure", widget: "object", fields:[{label: "Title", name: "title", widget: "string"}, {label: "Text", name: "text", widget: "text"}] }
          - {label: "Locations", name: "locations", widget: "object", fields:[{label: "Title", name: "title", widget: "string"}, {label: "Text", name: "text", widget: "text"},{label: "Places", name: "places", widget: "list", fields:[{label: "Label", name: "label", widget: "string"}]}] }
          - {label: "Expansion", name: "expansion", widget: "object", fields:[{label: "Title", name: "title", widget: "string"}, {label: "Left Paragraph", name: "left_paragraph", widget: "text"}, {label: "Right Parahraph", name: "right_parahraph", widget: "text"} ] }
          - {label: "Meta Title", name: "meta_title", widget: "string"}
          - {label: "Meta Description", name: "meta_description", widget: "text"}
      - file: "src/pages/brands/index.md"
        label: "Brands" 
        name: "brands"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "brand-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Image", name: hero_image, widget: image}
          - {label: "Page Description", name: "page_description", widget: "object", fields:[{label: "Title", name: "title", widget: "string"}, {label: "Text", name: "text", widget: "text"}] }
          - {label: "Brands", name: "brands", widget: "object", fields:[{label: "Brands", name: "blurbs", widget: "list", fields:[{label: "Title", name: "title", widget: "string"}, {label: "Logo", name: "logo", widget: "image"}, {label: "Link", name: "url", widget: "string"}, {label: "Description", name: "text", widget: "text"}]}] }
          - {label: "Meta Title", name: "meta_title", widget: "string"}
          - {label: "Meta Description", name: "meta_description", widget: "text"}
      - file: "src/pages/solutions/index.md"
        label: "Solutions" 
        name: "solutions"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "solutions-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Image", name: hero_image, widget: image}
          - {label: "Page Description", name: "page_description", widget: "object", fields:[{label: "Title", name: "title", widget: "string"}, {label: "Text", name: "text", widget: "text"}] }
          - {label: "Solutions", name: "solutions", widget: "object", fields:[{label: "Solutions", name: "blurbs", widget: "list", fields:[{label: "Title", name: "title", widget: "string"}, {label: "Logo", name: "logo", widget: "image"}, {label: "Description", name: "text", widget: "text"}]}] }
          - {label: "Meta Title", name: "meta_title", widget: "string"}
          - {label: "Meta Description", name: "meta_description", widget: "text"}
      - file: "src/pages/contact/index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: Title, name: title, widget: string}
          - {label: "Hero Image", name: hero_image, widget: image}
          - {label: "Page Description", name: "page_description", widget: "object", fields:[{label: "Title", name: "title", widget: "string"}, {label: "Text", name: "text", widget: "text"}] }
          - {label: "Contact Form", name: "contact_form", widget: "object", fields:[{label: "Title", name: "title", widget: "string"}, {label: "Text", name: "text", widget: "text"}] }
          - {label: "Hire", name: "hire", widget: "object", fields:[{label: "Title", name: "title", widget: "string"}, {label: "Text", name: "text", widget: "text"}, {label: "Email", name: "email", widget: "string"}] }
          - {label: "Contact Details", name: "contact_details", widget: "object", fields:[{label: "Address", name: "address", widget: "string"}, {label: "telephone", name: "telephone", widget: "text"}, {label: "Fax", name: "fax", widget: "string"}, {label: "Mobile", name: "mobile", widget: "string"}] }
          - {label: Map, name: map, widget: string}
          - {label: "Meta Title", name: "meta_title", widget: "string"}
          - {label: "Meta Description", name: "meta_description", widget: "text"}
  - name: "blog"
    label: "Blog"
    editor:
      preview: false
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Meta Title", name: "meta_title", widget: "string"}
      - {label: "Meta Description", name: "meta_description", widget: "text"}
  - name: "projects"
    label: "Projects"
    editor:
      preview: false
    folder: "src/pages/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Meta Title", name: "meta_title", widget: "string"}
      - {label: "Meta Description", name: "meta_description", widget: "text"}